version: '3'

services:
  binary-encoding-api:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: binary-encoding-api
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev